version: "3.8"

services:
  nature:
    container_name: nature
    build:
      context: ../
    ports:
      - '9000:9000'
    volumes:
      - ../htdocs:/var/www/html:rw
    depends_on:
      - database
      - redis
    links:
      - redis

  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db_mc
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '9006:3306'

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - database
    ports:
      - "9001:8080"

  redis:
    container_name: mc-redis
    image: redis
#    volumes:
#      - ../supervisor/conf.d/redis-server.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "9379:6379"

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '9002:80'
    volumes:
      - ../htdocs:/var/www/html:rw
      - ../playbooks/templates/test/etc/nginx/conf.d/default.conf.j2:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - nature
      - database
      - redis

volumes:
  database: